using System.Collections.Generic;

namespace EagleMoney.NET.Library
{
    public interface ICurrency
    { 
        string Code { get; init;  }

        string Number { get; init;  }

        string Sign { get; init; }
        
        int DefaultFractionDigits { get; init; }
        
        HashSet<string> Countries { get; init; }

        string ToString();

        static string AED { get; }
        static string AFN { get; }
        static string ALL { get; }
        static string AMD { get; }
        static string ANG { get; }
        static string AOA { get; }
        static string ARS { get; }
        static string AUD { get; }
        static string AWG { get; }
        static string AZN { get; }
        static string BAM { get; }
        static string BBD { get; }
        static string BDT { get; }
        static string BGN { get; }
        static string BHD { get; }
        static string BIF { get; }
        static string BMD { get; }
        static string BND { get; }
        static string BOB { get; }
        static string BOV { get; }
        static string BRL { get; }
        static string BSD { get; }
        static string BTN { get; }
        static string BWP { get; }
        static string BYN { get; }
        static string BZD { get; }
        static string CAD { get; }
        static string CDF { get; }
        static string CHE { get; }
        static string CHF { get; }
        static string CHW { get; }
        static string CLF { get; }
        static string CLP { get; }
        static string CNY { get; }
        static string COP { get; }
        static string COU { get; }
        static string CRC { get; }
        static string CUC { get; }
        static string CUP { get; }
        static string CVE { get; }
        static string CZK { get; }
        static string DJF { get; }
        static string DKK { get; }
        static string DOP { get; }
        static string DZD { get; }
        static string EGP { get; }
        static string ERN { get; }
        static string ETB { get; }
        static string EUR { get; }
        static string FJD { get; }
        static string FKP { get; }
        static string GBP { get; }
        static string GEL { get; }
        static string GHS { get; }
        static string GIP { get; }
        static string GMD { get; }
        static string GNF { get; }
        static string GTQ { get; }
        static string GYD { get; }
        static string HKD { get; }
        static string HNL { get; }
        static string HRK { get; }
        static string HTG { get; }
        static string HUF { get; }
        static string IDR { get; }
        static string ILS { get; }
        static string INR { get; }
        static string IQD { get; }
        static string IRR { get; }
        static string ISK { get; }
        static string JMD { get; }
        static string JOD { get; }
        static string JPY { get; }
        static string KES { get; }
        static string KGS { get; }
        static string KHR { get; }
        static string KMF { get; }
        static string KPW { get; }
        static string KRW { get; }
        static string KWD { get; }
        static string KYD { get; }
        static string KZT { get; }
        static string LAK { get; }
        static string LBP { get; }
        static string LKR { get; }
        static string LRD { get; }
        static string LSL { get; }
        static string LYD { get; }
        static string MAD { get; }
        static string MDL { get; }
        static string MGA { get; }
        static string MKD { get; }
        static string MMK { get; }
        static string MNT { get; }
        static string MOP { get; }
        static string MRU { get; }
        static string MUR { get; }
        static string MVR { get; }
        static string MWK { get; }
        static string MXN { get; }
        static string MXV { get; }
        static string MYR { get; }
        static string MZN { get; }
        static string NAD { get; }
        static string NGN { get; }
        static string NIO { get; }
        static string NOK { get; }
        static string NPR { get; }
        static string NZD { get; }
        static string OMR { get; }
        static string PAB { get; }
        static string PEN { get; }
        static string PGK { get; }
        static string PHP { get; }
        static string PKR { get; }
        static string PLN { get; }
        static string PYG { get; }
        static string QAR { get; }
        static string RON { get; }
        static string RSD { get; }
        static string RUB { get; }
        static string RWF { get; }
        static string SAR { get; }
        static string SBD { get; }
        static string SCR { get; }
        static string SDG { get; }
        static string SEK { get; }
        static string SGD { get; }
        static string SHP { get; }
        static string SLL { get; }
        static string SOS { get; }
        static string SRD { get; }
        static string SSP { get; }
        static string STN { get; }
        static string SVC { get; }
        static string SYP { get; }
        static string SZL { get; }
        static string THB { get; }
        static string TJS { get; }
        static string TMT { get; }
        static string TND { get; }
        static string TOP { get; }
        static string TRY { get; }
        static string TTD { get; }
        static string TWD { get; }
        static string TZS { get; }
        static string UAH { get; }
        static string UGX { get; }
        static string USD { get; }
        static string USN { get; }
        static string UYI { get; }
        static string UYU { get; }
        static string UYW { get; }
        static string UZS { get; }
        static string VES { get; }
        static string VND { get; }
        static string VUV { get; }
        static string WST { get; }
        static string XAF { get; }
        static string XCD { get; }
        static string XOF { get; }
        static string XPF { get; }
        static string YER { get; }
        static string ZAR { get; }
        static string ZMW { get; }
        static string ZWL { get; }
    }
}